### ISSUE TITLE
☀️Sujets Météo du web

### ISSUE THREAD

**Issue by EmmanuelDemey** [les-briques-du-web/notes#1]
- [ ] [Ivy Internals](https://blog.angular.io/ivys-internal-data-structures-f410509c7480)
- [ ] [Typescript 4.2](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#breaking-changes) 
- [ ] [open-web-docs](https://dev.to/wassimchegham/introducing-open-web-docs-4g1m)
- [ ] [Import maps dans Chrome](https://www.chromestatus.com/feature/5315286962012160)
- [ ] [early release de Lit 3.0](https://www.polymer-project.org/blog/2020-09-22-lit-element-and-lit-html-next-preview)
- [ ] [1 hour interview with Brendan Eich](https://www.youtube.com/watch?v=krB0enBeSiE)
- [ ] [Deno v1.8](https://deno.land/posts/v1.8)
- [ ] [Chrome Faster Release Cycle](https://developer.chrome.com/blog/faster-release-cycle/)
- [ ] [Typescript new handbook](https://devblogs.microsoft.com/typescript/announcing-the-new-typescript-handbook/)
- [ ] [Git vulnerability](https://github.blog/2021-03-09-git-clone-vulnerability-announced/)
- [ ] [@nodejs/undici](https://github.com/nodejs/undici) (preview)
- [ ] [vscode 1.54](https://youtu.be/GhS8QnaZX5k)

**Comment by noelmace** [comment]
Vous voudriez traiter quel type de sujet ?
On commente et on :+1:  ou on édite tous directement la liste ?

Ce qui me passe par la tête :
- [JSPM & Import Maps](https://jspm.org/import-map-cdn)
- [Total Cookie Protection](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/)

**Comment by jlengrand** [comment]
- [ ] [early release de Lit 3.0](https://www.polymer-project.org/blog/2020-09-22-lit-element-and-lit-html-next-preview)

**Comment by jlengrand** [comment]
T'avais pas un truc sur Snowpack @EmmanuelDemey  ?

**Comment by nweldev** [comment]
- [ ] [Import maps dans Chrome](https://www.chromestatus.com/feature/5315286962012160)

**Comment by EmmanuelDemey** [comment]
@jlengrand oui mais ce n'est pas dans l'issue Météo du web Non ?

**Comment by EmmanuelDemey** [comment]
@jlengrand Je viens de créer une issue spécifique pour le contenu du stream. Ce ticket n'est juste la que pour la météo du Web.

**Comment by jlengrand** [comment]
Je n'étais plus certain :). Merci!

**Comment by jefBinomed** [comment]
https://github.com/angular/angular/issues/41085 issue à propos d'angular et des PWA... Warning à peut être indiquer ?

**Comment by manekinekko** [comment]
Merci @jefBinomed Je propose de déplacer cela dans une autre émission. 

Je propose d'ailleur de créer une nouvelle émission qui serait nommée : "Le bug de trop !". Le but serait de présenter en détails un (et un seul) bug majeur d'une techno/browser dont les devs devraient être au courant. Souvent, dans la plus part de projets, on tombe sur des soucis mais on ne sait pas si c'est un bug dans le tool, dans le projet, dans le navigateur...

wdyt @jlengrand @LostInBrittany ?

**Comment by nweldev** [comment]
Ménage des issues.

Suggestion de @manekinekko déplacée dans https://github.com/les-briques-du-web/notes/issues/25
