### ISSUE TITLE
☀️ Météo du web S01E01

### ISSUE THREAD

**Issue by jlengrand** [les-briques-du-web/notes#10]
Tu veux nous mettre un teaser des sujets que tu vas traiter ou pas?

**Comment by manekinekko** [comment]
Je penses présenter 5 sujets  = 1 minute par sujet.
Je piocherais une partie des sujets depuis #1 que je continue d'alimenter (en mettant à jour l'OP).

**Comment by manekinekko** [comment]
En attendant que le repo soit crée, je met le script ici pour l'émission du Mardi 16.

<details>
<summary>Meteo du Web 16/03/2021</summary>

# Release

## [Typescript 4.2](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/)

Plus d'une 10aine de mise à jour et breaking changes.

- L'operateur in est maintenant plus strict (`"foo" in 42`)
-  `--explainFiles` vous permet de comprendre la structure de votre application (les deps...)
- Breaking chages:`noImplicitAny` declenche une erreur sur les instructions `yield` (generators)  

## [early release de Lit 3.0](https://www.polymer-project.org/blog/2020-09-22-lit-element-and-lit-html-next-preview)

Une version de preview des prochaines versions de LitElement 3 et lit-html 2.

## [Deno v1.8](https://deno.land/posts/v1.8)

1.8 propose : 
- un support experimental de WebGPU
- l'API Intl est maintenant built-in (i18n) 
- l'AI import maps stabilisée
- possible de fetch des modules privés

## [vscode 1.54](https://youtu.be/GhS8QnaZX5k)

1.54 propose:
- support officiel du nouveau proc M1 Apple Silicon
- amelioration de l'accessibilité
- terminal integré est restauré suite au reload window.

Lien vers la video de 30min par Burke et Eric Amodio.

# Actu

## [Chromium Faster Release Cycle](https://blog.chromium.org/2021/03/speeding-up-release-cycle.html/)

Chromium, Chrome et Edge accélèrent le cycle de release à 4 semaines,  a partir de Q3 of 2021.

## [Typescript new handbook](https://devblogs.microsoft.com/typescript/announcing-the-new-typescript-handbook/)

Si vous voulez apprendre TypeScript, le nouveau livre blanc a été mise a jour et est téléchargeable gratuitement.

## [@nodejs/undici](https://github.com/nodejs/undici) (preview)

Une nouvelle implementation du client HTTP ecrite from scratch. A surveiller de pres ;) 

## [Import maps dans Chrome](https://www.chromestatus.com/feature/5315286962012160)

Les import maps sont un nouveau standard en cours d'experimentation au sein du WICG (Web Platform Incubator Community Group. Le but etant de controler le chagement des imports JS via un fichier manifest.

## [Ivy Internals](https://blog.angular.io/ivys-internal-data-structures-f410509c7480)

Un article de 5min sur le fonctionnement interne d'Ivy, le nouveau moteur de rendu d'Angular. Dans cet article Misko parle des 3 structures de données de donnés au coeur d'Ivy: Template, Logical Tree, and Render Tree. 

## [open-web-docs](https://dev.to/wassimchegham/introducing-open-web-docs-4g1m)

Open Web Docs est un nouveau projet en collaboration entre Google, Microsoft, Mozilla, Coil, W3C, Samsung, et Igalia, pour aider et supporter la maintenance des differentes organisation de documentation techniques telles que MDN. 

</details>
