### ISSUE TITLE
☀️ Météo du web S01E02

### ISSUE THREAD

**Issue by manekinekko** [les-briques-du-web/notes#16]
- Nouveautés ES2021 (https://twitter.com/manekinekko/status/1372838850637221891)
- HTTPS par defaut dans Chromium v90 (https://blog.chromium.org/2021/03/a-safer-default-for-navigation-https.html)
- Intent to Experiment: File Handling API (https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Fb-NdCvbgmU/68nHOaFPBQAJ)
- V8 nouvelle version v9 (https://v8.dev/blog/v8-release-90)
- Les 10 prochaines années de Node.kjs - Participez au sondage (https://www.surveymonkey.com/r/86SSY9Q)
- Node.js v15.12 (https://nodeweekly.com/link/105223/75d176944d) 
- Svelte kit is in public beta (https://svelte.dev/blog/sveltekit-beta)
- Create a design system with Lion web components (https://medium.com/ing-blog/create-a-design-system-with-lion-web-components-b9ff86a17a84)

**Comment by EmmanuelDemey** [comment]
Node.js v15.12 https://nodeweekly.com/link/105223/75d176944d

**Comment by EmmanuelDemey** [comment]
Svelte kit is in public beta 

https://svelte.dev/blog/sveltekit-beta

**Comment by EmmanuelDemey** [comment]
The end of AMP https://www.lafoo.com/the-end-of-amp/

**Comment by manekinekko** [comment]
@EmmanuelDemey que penses-tu de déplacer l'article sur AMP vers autre emission ? Ca me parait hors sujet par rapport au theme de la chronique. Tu en dis quoi ?

**Comment by EmmanuelDemey** [comment]
Pas de soucis

**Comment by manekinekko** [comment]
@EmmanuelDemey tu as pu présenter toutes les news de cette issue lord du dernier episode ?

**Comment by EmmanuelDemey** [comment]
Yes
