### ISSUE TITLE
🎙 Les chroniques

### ISSUE THREAD

**Issue by nweldev** [les-briques-du-web/notes#2]
Chroniques courtes (5/10 minutes) présentées (en roulement) d'une émission à l'autre.

> En plus du sujet principal avec invité·e·s, de l'intro & outro, etc.

## Orga

- 3 (ou 4 ~= 20 minutes) chroniques par émission.
- un ou deux (histoire de palier aux indisponibilités) référents pour chaque chronique
- la chronique n'est pas forcément présentée par le référent (faut du roulement)
- le(s) référent(s) se chargerent d'organiser le truc (choisir un sujet, voir si la chronique est prête pour une émission, qui la présente, aide à l'écriture et relecture d'un script si besoin, etc.)

## Liste des chroniques

| nom (temporaire) | issue | durée | principe | référents |
|-|-|-|-|-|
| Météo du Web | #1 | 5'  | actualités  | @manekinekko |
| le projet de la semaine | | 5'/10' | outil / lib interessant | @EmmanuelDemey |
| les anecdotes historiques | #5 | 5' | évoquer un fait marquant mais peu connu de l'histoire du web | @noelmace |
| Le focus API | #13 |  5'/10' |  présenter un aspect peu connu de JS, CSS, HTML, Web API, etc. | @jefBinomed  & @hsablonniere
| Rex / Invité de la semaine | #4 | 20'/25' |   | @jlengrand / @LostInBrittany |

**Comment by nweldev** [comment]
Pour "le truc que tu savais pas", je peux avoir pas mal d'idée côté standards / Web API.

:heavy_plus_sign: une chronique "anecdotes historiques" ? j'ai aussi du stock de ce côté.

**Comment by jlengrand** [comment]
Ha, c'est bon ça les anecdotes historiques!

**Comment by jlengrand** [comment]
- [ ] Le sujet principal, avec invité(s), sur un sujet différent à chaque fois - 20 /25
- [ ] Le retour d'expérience sur un sujet précis - Peut-être court en fonction du sujet?

**Comment by nweldev** [comment]
Le ReX c'est une très bonne idée en effet. Faudrait toujours s'assurer que l'émission ai au moins un truc qui "encre dans le réel" pour le public. Compliqué en moins de 15 minutes non ?

**Comment by jlengrand** [comment]
Agreed. Je pense que 80% du temps ce sera avec l'invité principal. Je pensais aussi à par example : "Rex Lit 3.0 preview, est ce que c est trop tôt pour switcher où non", ce genre de trucs. Ça peut être court

**Comment by nweldev** [comment]
:+1: pour le ReX Lit 3.0 (on dit pas plutôt [Lit 2.0](https://github.com/Polymer/lit-html/tree/lit-next/packages/lit) ?). Pour la durée, ça dépend si on veut lancer un débat ou non :smile: 

Au passage, j'ai édité l'issue pour faire la distinction entre les éléments fil rouge à présenter à chaque émission et les "véritables" chroniques (en roulement).

**Comment by jlengrand** [comment]
Est ce que la météo c est un truc qu on aurait à chaque fois? Si c'est la météo c'est probablement logique de l avoir au minima une fois par mois non?

**Comment by manekinekko** [comment]
Je pense que la météo sera une des émissions récurrente, à chaque émission. Vu les news du front, je pense qu'on a de la matiere.

**Comment by nweldev** [comment]
@manekinekko Ça tien sur 5 minutes tu penses ? Ça me parait un bon rythme si on le fait à chaque émission.

:heavy_plus_sign: @EmmanuelDemey sur "le projet de la semaine" avec Snowpack pour la première émission en 10 minutes (#6). Référent pour les suivantes ou on voit après ?

**Comment by manekinekko** [comment]
@noelmace la meteo devrait etre limitee à 5min grand max. On trouvera le bon format apres l'episode pilote.

**Comment by jefBinomed** [comment]
Le sujet peu connu du web, ça va me forcer à creuser un peu :p ça me dit bien de prendre ça :)

**Comment by hsablonniere** [comment]
@jefBinomed je peux aussi faire en roulement avec toi sur les sujets peu connus

**Comment by jlengrand** [comment]
Du coup si j'ai bien compris @LostInBrittany et moi on ferait l interview centrale / rex et les intros outros quand nécessaires? Vu que c'etait un peu la dessus qu on était parti au tout départ

EDIT: Bon bah je nous place comme ça en attendant

**Comment by nweldev** [comment]
@jefBinomed @hsablonniere IMO, vu qu'on aura tous envie et du stock pour contribuer sur plusieurs rubriques, ça peut être pas mal de ne pas fixer les intervenants, mais juste le "référent".

Genre une émission je fais l'histo et vous le "truc", et une autre fois c'est l'inverse. En plus ça évitera la routine.

Mais le/les référents vont présenter la première chronique a priori.

**Comment by jefBinomed** [comment]
Yes indeed :)

Dans les rubriques, on pourra aussi se faire une rubrique "chasse et pêche" pour parler de temps en temps des features du project Fugu :D 🐡

**Comment by nweldev** [comment]
Fugu faudra l'intégrer à la météo d'ailleurs. Mais une chronique de 10 minutes là dessus pour introduire le sujet ce serait pas mal en effet.

**Comment by hsablonniere** [comment]
@jefBinomed Pour le "présenter un aspect peu connu de JS, CSS, HTML, Web API, etc." je vois ça comme une occasion de faire une "zoom" ou "focus" sur une API (HTML/CSS/JS/Web) pas/peu connue récente ou pas.

Si j'ai bien compris, on se concentre sur des API ou fonctionnalités standard.

Voici des exemples qui me viennent en tête :

* L'API standard URL (et son parseur d'URL et de query string)
* Fetch et abort
* Les options sur le addEventListener
* Les labels en JS (qui on été détourné par Svelte)
* Intl.NumberFormat
* setTimeout (et ses particularité) cf la vidéo de Jake et Surma
* Les balises OpenGraph

Pour le titre, ça pourrait être :

* Le focus API de la semaine
  * C'est peut-être confusant "API" pour parler d'une fonctionnalité d'HTML par exemple
* Le zoom API de la semaine
* Le truc méconnu de la semaine

**Comment by manekinekko** [comment]
Quelques éléments à prendre en compte pour le choix du titre:
- Les épisodes sont 2 fois par mois, donc "... de la semaine" risque de ne pas coller.
- Peut être éviter les termes négatifs comme "méconnu..." ca pourrait faire passer les auditeurs pour des nulls. "focus" me parait bcp plus adapté.

**Comment by jlengrand** [comment]
J'ai changé en 'le projet qui fait rêver' juste parce que ça rime. Que quelqu'un trouve mieux par pitié XD

EDIT : pareil pour le 'feature focus'

**Comment by jefBinomed** [comment]
Dans les idées @hsablonniere , on pourra aussi parler de :
* [] comment renvoyer autre chose que des strings avec les strings literals LIT POWA !! (DU JSX en standard !)
* [] Les proxies et la façon dont on peut mettre en place des règles de controles
* [] Les property descriptor qui peuvent rendre des objets ou propriétés immutables
* [] Faire un sujet sur la différences entre properties et attributes quand on parle de web components
* [] Micro Task vs Macro Task et Queue Task dans l'event loop ou comment créer du code bloquant à base d'appels asynchrones :D
* [] Les generateurs qui peuvent ressembler à rxJS dans une certaines mesure
* [] Qqes tips sur les protypes qui restent la base malgré les classes ! et donc la possibilité de faire muter des classes dynamiquement
* [] La copie d'objets avec le spread operateur
* [] Quelle différence entre async et une promesse dans l'event loop

Je tacherais de trouver d'autres idées sinon, j'aime bien l'idée aussi de prendre exemple sur les vidéos de Jake et Surma !

**Comment by jefBinomed** [comment]
En rubrique qui reviendrait pas forcément régulièrement mais qui pourrait être intéressante, un truc du type "ça vient de TCpasser" pour lister les dernières features passées en stage 4 dans le TC39, spéciale dédicace à Olivier

**Comment by manekinekko** [comment]
@jefBinomed pourquoi ne pas partager les news TC39 dans la meteo du Web ? Surtout qu'il risque de ne pas y avoir tant que ca par moi des nouvelles API qui passent en S4 😛

**Comment by jefBinomed** [comment]
> @jefBinomed pourquoi ne pas partager les news TC39 dans la meteo du Web ? Surtout qu'il risque de ne pas y avoir tant que ca par moi des nouvelles API qui passent en S4 😛

J'avoue que j'ai hésité en effet :)

**Comment by hsablonniere** [comment]
@jefBinomed Je sur-kiffe tes propositions, à chaque item, j'étais "mais oui, mais oui".

**Comment by jlengrand** [comment]
> @jefBinomed pourquoi ne pas partager les news TC39 dans la meteo du Web ? Surtout qu'il risque de ne pas y avoir tant que ca par moi des nouvelles API qui passent en S4 😛

Après le nom de rubrique reste intéressant en lui-même XD

**Comment by hsablonniere** [comment]
Je viens de créer une issue pour discuter de la rubrique "Focus API" : https://github.com/les-briques-du-web/notes/issues/13

@jefBinomed On va pouvoir discuter des idées directement là bas.

@noelmace Tu peux maj cette issue (#2) avec le liens vers la #13 ?

**Comment by nweldev** [comment]
@hsablonniere :heavy_check_mark: done

**Comment by nweldev** [comment]
Je pense qu'on a bien établit les chroniques à présents.

Je ferme donc cette issue, et propose d'ouvrir une nouvelle issue avec le label "discussion" pour suggérer de nouvelles chroniques à l'avenir.
