### ISSUE TITLE
🗒️ Idées d'invités et sujets principaux

### ISSUE THREAD

**Issue by jlengrand** [les-briques-du-web/notes#4]
Pour trouver des invité(e)s. Brainstorm initial avec Horacio : 

Accessibilité : Fanny Demy & Cecile Freyd-Foucault
Intro Buildless? Pourquoi?
PWA and capabilities
Snowpack
Web components librairies - standards intro
Interop avec les + gros frameworks - 
Reutilsabilite en front
Design systems
Micro front-ends
Intro a technos specifiques - 
Retours experience de l industrie
State management
Serverless 
Typescript ?
JAM stack

**Comment by nweldev** [comment]
:+1: pour A11Y - se serait pas mal d'y consacrer une émission pour lancer le truc, puis d'en faire une chronique

Pour une première émission, intro au buildless ça me semble pas mal.

**Comment by hsablonniere** [comment]
Modules
Bundlers
Web perf
Sécu
Eslint
Vite

**Comment by jefBinomed** [comment]
Houdini CSS :p 
Custom Properties & Part & Theme pour styliser les webcomponents
WASM et les lambdas 
Gestion des cookies ?
Le debuggage et le web
Offline Cookbook
PWA ou Web Moderne ?

**Comment by hsablonniere** [comment]
Idée d'invité : Boris Schapira pour parler de Web perf

**Comment by jlengrand** [comment]
> Idée d'invité : Boris Schapira pour parler de Web perf

Tu peux nous confirmer si il est chaud et pour quel sujet exact? (et qui sera l'intervieweur principal?)

**Comment by nweldev** [comment]
Comme on discute ce genre de sujets dans les issues des épisodes et sur le discord, je ferme celle-ci, et propose qu'on ouvre une issue par invité si besoin.
