### ISSUE TITLE
📜 anecdotes historiques

### ISSUE THREAD

**Issue by nweldev** [les-briques-du-web/notes#5]
Présenter un évènement historique de l'histoire du Web marquant mais peu connu, en 5 minutes environs

Traiter le sujet sur un ton humoristique, en s'efforçant d'en faire sortir une "leçon importante".

Quelques idées en vrac :
- ça sert à quoi une RFC
- pourquoi le concept de "client léger" est important
- pourquoi on a besoin que Mozilla existe
- accessibilité (en prenant l'excuse des navigateurs en ligne de commande, par exemple)

J'ai consacré les deux premiers chapitres de mon livre à ce sujet (112 pages), donc j'ai de la matière.

## Épisodes

1. #8 "The Mother of all Demos" (2021-03-16 :heavy_check_mark: )

**Comment by hsablonniere** [comment]
J'aime bien pour le premier épisode ;-) :clap:

**Comment by nweldev** [comment]
Je ferai une issue par chronique si besoin, ou les discuterai directement dans l'issue de l'épisode.
