### ISSUE TITLE
Episode "pilote" : 16/03/2021

### ISSUE THREAD

**Issue by EmmanuelDemey** [les-briques-du-web/notes#6]
> **Edit** : mise à jour au fur et à mesure, pour organiser un peu. Rien n'est vraiment confirmé / gravé dans le marbre.

animation : @jlengrand & @LostInBrittany

1. présentation de l'émission et des participants : 10 minutes (pour faire très large)
2. chronique 1 : @manekinekko "La météo du Web" : #1 : 5 minutes 
3. chronique 2 : @EmmanuelDemey "Le projet de la semaine" : Snowpack : 10 minutes
4. chronique 3 : @noelmace "histoire" : "Mother of all demos" #5 : 5 minutes
5. Accessibilité avec Fanny Demy & Cecile Freyd-Foucault : 20 minutes (à confirmer)
6. la question du public (compliqué pour une 1ère) OU "le pick de l'invité (carte blanche)" : 5 minutes

**Comment by nweldev** [comment]
@EmmanuelDemey Snowpack en sujet principal (20 minutes) ou chronique (5 minutes) ?

**Comment by EmmanuelDemey** [comment]
On m'a donné 10mn :)

**Comment by hsablonniere** [comment]
Du coup qui participe ? Qui anime ?

**Comment by nweldev** [comment]
@hsablonniere si j'ai bien compris (j'évalue mes chances à 40% là tout de suite :laughing:)

> déplacé dans la description vu que la base était là

A mon avis pour la partie "interview de l'invité", plus on est de fou mieux c'est non (dans la limite du raisonnable) ? @LostInBrittany pensais à "le quotidien" comme exemple.

**Comment by noelmace** [comment]
@EmmanuelDemey on met à jour la description de l'issue avec un truc plus générique ? (genre : pour essayer d'organiser le boxon, c'est ici :rofl: )

**Comment by jlengrand** [comment]
Ca a l air nickel

* "interview de l invite". Je trouvais que 2 ca faisait deja bcp. En direct ça marcherait, mais sur un temps de 20 minutes avec un invité on se marcher/parler dessus a plein non? 
* on avait pas ça comme idée en premier invité? Accessibilité : Fanny Demy & Cecile Freyd-Foucault
* J'en viens a me demander si c est vraiment la peine d introduire tout le monde la premiere semaine. On nous verra bien au fil des rubriques non? Ca risque pas de faire catalogue tekken :)?

**Comment by nweldev** [comment]
- (edit : j'avais compris de travers) c'est sur qu'il faut organiser en mode "baton de parole" (les animateurs désignent qui peut parler)
- :100: pour Accessibilité : Fanny Demy & Cecile Freyd-Foucault
- pour le coup je pense à "par Jupiter" : en audio, c'est vrais que c'est beaucoup mieux d'avoir une première perception de qui est là (et idem quand c'est du stream depuis plusieurs endroits je pense), même si c'est juste pour faire 1/2 phrase. A la rigueur, un mode tekken ça s'assume aussi :wink: Par contre oui, la présentation de l'émission ça peut tenir en une phrase hein.

**Comment by hsablonniere** [comment]
Je crois que tu as fais une faute au nom de famille de Fanny :laughing:

**Comment by jlengrand** [comment]
@noelmace je suis en train de penser au format, tu peux me confimer ce que tu veux dire par "par jupiter "?

**Comment by jefBinomed** [comment]
de toute façon pour la première on est tous présents non ?

**Comment by nweldev** [comment]
@jlengrand https://www.franceinter.fr/emissions/par-jupiter
émission radio de 45-50 minutes autour d'un invité, avec des chroniques de 5 minutes en roulement + une systématique type "actu" ("le journal de 17h17")
évidemment sur le ton et les sujets ça n'a rien à voir avec nous, mais sur la forme je pense qu'on est assez proche
Pour le coup, je pensais à l'intro de chaque émission, après leur petit sketch, où ils présentent en fin de "sommaire" chaque personne présente très rapidement, qui dit de quoi parlera sa chronique.

**Comment by nweldev** [comment]
Et pour ce qui est de la gestion de la prise de parole, j'aime beaucoup le travail de Nicolas Martin, qui anime des émissions comme ["La méthode scientifique"](https://www.franceculture.fr/emissions/la-methode-scientifique) sur France Culture.

**Comment by jlengrand** [comment]
Super, merci des références. Ça m'intéresse vraiment de voir comment on peut avoir le plus de dynamisme possible sans que ce soit le boxon.

**Comment by nweldev** [comment]
D'ailleurs je viens de réaliser : Il y a toujours un temps à prévoir pour les réactions entre chaque chroniques. J'ai peur que ce soit pas super dynamique l’enchaînement de 3 chroniques, ou alors qu'on manque de temps au final.

Du style :

| time code | sujet
|-|-|
| 00 | "sommaire" &  introduction du sujet avec les invités |
| 05 | météo du Web | 
| 10 | _réactions à l'actu_ |
| 15 | Le projet de la semaine |
| 25 | **A11Y** (25 minutes) | 
| 50 | "archives" |
| 55 | _réactions_ |
| 60 | conclusion avec les invités |
| 65 | FIN |

Je réalise au passage que le total fait 55 minutes dans l'issue :confused: 
@EmmanuelDemey On garde 10 minutes  pour Snowpack ?

**Comment by jefBinomed** [comment]
du coup pour cette session, on n'inclue pas encore la feature JS ? ça me va c'est juse pour qu'on soit sur de quand préparer les choses ^^

**Comment by jlengrand** [comment]
Ça dépend juste du temps qu'on a. Avec les archives et le projet, on est calé pour 45 minutes. Tu te réserves un  slot pour dans deux semaines? 

EDIT : En tout cas c'est le cas actuellement, à moins que quelqu'un trouve un moyen de diluer l'échelle du temps :P

**Comment by EmmanuelDemey** [comment]
@noelmace je m'adapte :D

**Comment by hsablonniere** [comment]
Feedbacks du chat:

> Il serait mieux de préparer des slides avec des images/diagrammes même si c'est pour 10 minutes

Ça peut être des slides mais ça pourrait aussi être du share screen avec la page d'un site de doc ou autre...

> Niveau habillage, ça serait cool d'avoir le nom de la personne pendant toute l'intervention

Il semblerait qu'on ne puisse pas afficher le nom + le titre de la chronique en même temps. Pourquoi pas ajouter le chroniqueur ds le titre de la chronique...

> Peut-être + d'interactivité la prochaine fois ?

> Format sympa, un petit échange question/réponse peut-être ?

> Puisqu'on parlait d'accessibilité, est-ce qu'il y aura des sous-titres ?

**Comment by manekinekko** [comment]
Pour les slides ca risque de faire bizarre si on veut faire du podcast audio !?

**Comment by jlengrand** [comment]
Dans le débrief rapide on a conclu la même chose @manekinekko 

EDIT: 

On a aussi mentionné le fait d'avoir 15 minutes avec tout le monde à l'écran après la 'fin' de l'émission pour avoir une partie super interactive, mais les viewers qui veulent peuvent partir.

> Il semblerait qu'on ne puisse pas afficher le nom + le titre de la chronique en même temps. Pourquoi pas ajouter le chroniqueur ds le titre de la chronique... - 


Ca risque de faire long mais je teste la prochaine fois!

Ça me fait penser aussi que si on veut faire du pur audio il faudrait probablement qu on soit un peu plus présent sur les noms des gens

**Comment by manekinekko** [comment]
> Ça me fait penser aussi que si on veut faire du pur audio il faudrait probablement qu on soit un peu plus présent sur les noms des gens

Ca me va. Surtout que je n'ai pas été présenté lors de l'épisode (et je ne me suis pas présenté non plus – vu les 5min de la chronique) 😂❤️

**Comment by jlengrand** [comment]
Mais ouiiiii, et je t'ai même coupé à la fin :s. C'est le problème d'essuyer les plâtres ça. Promis on fait mieux dans deux semaines!

**Comment by manekinekko** [comment]
Aucun souci, c'est du détail. L'essentiel c'est que les gens apprécient le contenu 😉
