### ISSUE TITLE
📜 anecdote 1 : Alors, qui a inventé le web à votre avis ?

### ISSUE THREAD

**Issue by jlengrand** [les-briques-du-web/notes#8]
**1968 : Douglas Engelbart & "The mother of all demo"**

première intégration du concept d'hypertexte, mais aussi de plein d'autres

**Le "truc à retenir"** : les idées présentées comme "nouvelles" le sont rarement. Il y a toujours des prédécesseurs qui ont accomplit un travail de malade.

![image](https://user-images.githubusercontent.com/7578400/109935478-ee1dc380-7ccd-11eb-8e97-9c7804d84b39.png)

### sources

<p><div class="csl-right-inline">Engelbart D. <span>« Workstation History and the Augmented Knowledge Workshop »</span>. In : <em>Proceedings of the ACM Conference on the History of Personal Workstations</em> (En ligne). Association for Computing Machinery, p. 73‑83. Disponible sur : <a href="https://www.dougengelbart.org/content/view/112/000/">https://www.dougengelbart.org/content/view/112/000/</a> (consulté le 24 octobre 2020)ISBN : <a href="https://worldcat.org/isbn/0-89791-176-8">0-89791-176-8</a>.</div></p>
</div>

<p><div class="csl-right-inline"><span>« thedemo.org »</span>. In : <em>Doug Engelbart Institute</em> (En ligne). Disponible sur : <a href="https://www.dougengelbart.org/content/view/209/448/">https://www.dougengelbart.org/content/view/209/448/</a> (consulté le 24 octobre 2020)</div></p>
</div>

**Comment by nweldev** [comment]
A priori je devrais pouvoir me libérer du temps pour écrire le script entre mercredi et vendredi, histoire de faire la review le weekend prochain et être prêt pour le 16 mars.

**Comment by nweldev** [comment]
@jlengrand @LostInBrittany
Blog post publié : https://fullweb.dev/blog/qui-a-invente-hypertexte
avec le tweet qui va bien : https://twitter.com/noel_mace/status/1372150134897803267
