### ISSUE TITLE
Snowpack

### ISSUE THREAD

**Issue by jlengrand** [les-briques-du-web/notes#9]

**Comment by hsablonniere** [comment]
Suggestion : parler de web-dev-server et vite (bon après, en 10min, c'est sûrement impossible mais je suggère au cas où)

**Comment by jlengrand** [comment]
au pire on peut faire un épisode dédié @hsablonniere

**Comment by nweldev** [comment]
Un épisode dédié à modern-web / open-wc ça semblerait logique en effet.

**Comment by EmmanuelDemey** [comment]
Je voulais en conclusion parler de Vite, pour donner envie pour une autre rubrique dans un prochaine episode. Sans entrer en détail.

**Comment by EmmanuelDemey** [comment]
@LostInBrittany @jlengrand  voici les liens que nous pouvons ajouter à ma rubriques : 

* [SnowPack](https://www.snowpack.dev/)
* [Podcast sur Pika et Snowpack](https://thewebplatformpodcast.com/200-pika-and-snowpack)
* [Speakeasy JS – Snowpack: Faster web tooling, powered by ESM ](https://www.youtube.com/watch?v=PJcfKX_PKaM)
